# Generated by Django 2.2.7 on 2020-10-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bussines_name', models.CharField(max_length=50)),
                ('Full_name', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
