# Generated by Django 2.2.7 on 2020-10-28 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Bussines_name',
            new_name='Bussiness_name',
        ),
    ]
