# Generated by Django 2.2.7 on 2020-10-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='media_file',
            name='Headline',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='media_file',
            name='Image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='media_file',
            name='Logos',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='media_file',
            name='Domain',
            field=models.CharField(default='', max_length=50),
        ),
    ]
